Sort entries
yishn/chinese-tokenizer pull request #4
Opened 2019-06-07 05:41 UTC by TomClarkson

2019-06-07 05:43 UTC, TomClarkson commented
I'm not quite following the change to have two tries, one for simplified and one for traditional.

It does result in duplicate entries being returned.

2019-06-07 06:57 UTC, yishn requested changes
Thanks for the PR! I've left some comments.

2019-06-07 06:57 UTC, yishn commented on src/main.js
> +        const aIsOldVariant = a.english.includes("old variant of ");
Can you adhere to the style of the existing code?

- No semicolons
- Use `let` instead of `const` inside functions

2019-06-07 06:57 UTC, yishn commented on src/main.js
> +                matches: sortedEntries
In the old code, we're filtering out `traditional` and `simplified` fields. I'd like to keep it that way.

2019-06-07 07:07 UTC, yishn commented
> I'm not quite following the change to have two tries, one for simplified and one for traditional.

Take for example 么. This character is both a traditional character (pr. yāo) which simplified form is 幺. But in simplified Chinese 么 (pr. ma) is the simplification of 麼. If we do not have separate tries, we will get both yāo and ma which are two completely different characters.

> It does result in duplicate entries being returned.

In an ambiguous situation (e.g. input is one character) we're returning both traditional and simplified entries. We can just return traditional entries in that case to avoid any duplication.

2019-06-08 20:05 UTC, TomClarkson commented
Cheers for the feedback I have updated the PR :)

2019-06-09 09:28 UTC, yishn approved these changes

2019-06-09 09:32 UTC, yishn commented
@TomClarkson Somehow your new test fails in Travis. Can you take a look at it?

2019-06-14 07:25 UTC, yishn requested changes
Somehow your new test fails in Travis. Can you take a look at it?

2019-10-07 07:33 UTC, yishn commented
@TomClarkson Just a friendly reminder, that you still have this PR open. 🙂

2019-10-08 05:32 UTC, TomClarkson commented
Hey mate, I'm not quite sure why those tests are failing. 

I'll close for now, it will probably won't have time until next year unfortunately.

I'm thinking of making an open source reading app in 2020, I will let you know.

Thanks

2019-10-08 05:32 UTC, closed without merging